# This is a config for E2B sandbox template.
# You can use template ID (03fgxtd8trarp7pwqj5f) or template name (vibe-nextjs-44) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-44") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-44") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-44')

team_id = "67287243-1f29-40bb-9637-6b3613af9b07"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-44"
template_id = "03fgxtd8trarp7pwqj5f"
